name: Deploy

on:
  push:
    branches:
      # - "dev"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and build
        run: npm install --force && npm run build


  DeployDev:
    name: Deploy Test Environment
    if: github.event.ref == 'refs/head/dev'
    needs: [build]
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Deploy Dev
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.


  DeployLive:
    name: Deploy Live
    # if: github.event.ref == 'refs/head/main'
    needs: [build]
    runs-on: ubuntu-latest

    environment:
      name: live

    steps:
      - name: SSH
        run: install -m 600 -D /dev/null ~/.ssh/id_rsa; \
             bash -c 'echo "${{ secrets.DEPLOY_KEY }}" >  ~/.ssh/id_rsa'; \
             ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      
      - name: Deploy Live
        run: scp -r build ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR_LIVE }}

      
      - name: Cleanup
        run: rm -rf ~/.ssh